### ISSUE TITLE
Doesn't produce full final image

### ISSUE THREAD

**Issue by tomnookisgay** [DavidBuchanan314/tweetable-polyglot-png#1]
I took this image 
![toonoo](https://user-images.githubusercontent.com/49420027/111715042-fd9a2200-8820-11eb-990e-6bcb38abb8e8.png)
and embedded it with an mp3 of "Booty Wave" from the onion (lol they were the first mp3 and png I had in my downloads folder)
and had this as the final result
![senanbooty](https://user-images.githubusercontent.com/49420027/111715102-1e627780-8821-11eb-9550-b9f9622da46c.png)
as you can see, this is not the same image as the original, although the audio part of it still works if I add the .mp3 extension at the end. (you'll have to play it in vlc as the default windows mp3 player doesn't work with it)

In addition, just to double check, I got this image 
![Ticox](https://user-images.githubusercontent.com/49420027/111716803-cc235580-8824-11eb-82f5-f391a738f6a0.png)
and an mp3 of Toxic by Britney Spears with this as the result
![Toxic](https://user-images.githubusercontent.com/49420027/111716859-e826f700-8824-11eb-8a23-072f8cc99150.png)

**Comment by DavidBuchanan314** [comment]
Are you sure you're using the latest version of the script? It looks like these images have multiple IDAT chunks, the latter of which are being discarded. Assuming that's the problem, the latest version of the script should have this fixed already.

**Comment by tomnookisgay** [comment]
> Are you sure you're using the latest version of the script? It looks like these images have multiple IDAT chunks, the latter of which are being discarded. Assuming that's the problem, the latest version of the script should have this fixed already.

ooh yeah i was using the version of the script from the original twitter post. I got the new version, but now I keep getting this when I run the script `ERROR: Input files too big for cover image resolution.`
Just in case my files were too big, I reduced the mp3 bitrate to 64 kb/s which nearly halved the file size (becoming 1,539 KB, with the image being just over 100 KB already) but am still getting the same error.

**Comment by DavidBuchanan314** [comment]
The error message is correct, see the formula in the README

(Consider increasing the image resolution, and compressing it further by using a palette)
