### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cover.png'

### ISSUE THREAD

**Issue by XeroShi** [DavidBuchanan314/tweetable-polyglot-png#10]
I've been trying to use this tool but I can't figure out how to really use it.

I have a cover.png and a content.zip but I can't get an output. If I do
`python pack.py cover.png content.bin output.png`
I'll get the following:
`FileNotFoundError: [Errno 2] No such file or directory: 'cover.png'`
despite having a cover.png

**Comment by DavidBuchanan314** [comment]
I cannot reproduce the issue
