### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by makstona** [DavidBuchanan314/tweetable-polyglot-png#2]
com.github.stfalcon:swipeable-button:0.1.0'

**Comment by DavidBuchanan314** [comment]
I don't have an iOS device on-hand, so I'll need more details than that

**Comment by codenoid** [comment]
what is this?

**Comment by DavidBuchanan314** [comment]
a vague github issue?

**Comment by DavidBuchanan314** [comment]
I'm closing this until more details are added.
