### ISSUE TITLE
Also it doesn't work on Linkedin as well

### ISSUE THREAD

**Issue by ShivamJoker** [DavidBuchanan314/tweetable-polyglot-png#5]
Is there any way to make it happen, it converts the .png to .jpg

**Comment by dardysing69** [comment]
Limits
File()3000byts zip
.png
Or jpeg

Sent from my iPhone

On 21 Mar 2021, at 7:41 pm, Shivam ***@***.***> wrote:

﻿

Is there any way to make it happen, it converts the .png to .jpg

**Comment by thispsj** [comment]
@ShivamJoker it won't work on some services like LinkedIn (as you mentioned), WhatsApp, Reddit etc because they convert the pictures into jpg with suitable resolution. It will definitely work on services which don't do this conversion like Twitter,Discord, GitHub etc
