### ISSUE TITLE
MP3 file won't play

### ISSUE THREAD

**Issue by kodxana** [DavidBuchanan314/tweetable-polyglot-png#7]
I created image with embem mp3 file
```
Image size: 2765x4096px
Embedded file starts at offset 0x2a74c1
```
Issue is that after making png into mp3 it plays 10 sec of silence.

**Comment by Bochka999** [comment]
It's good question

**Comment by DavidBuchanan314** [comment]
Which media player did you use? Some will only see the PNG, and "play" a silent video of the image. There isn't really a way to avoid this.

**Comment by deevananaidoo00** [comment]
You can download an application called AIMP , from google play store![Screenshot_20210322-081928.png](https://user-images.githubusercontent.com/81121779/111948125-5a2e6300-8ae7-11eb-84ea- -f425ec97c57a.png) ~~its the best app I came across so far~~~~

**Comment by kodxana** [comment]
> Which media player did you use? Some will only see the PNG, and "play" a silent video of the image. There isn't really a way to avoid this.

VLC. And I seen image in background during playback of 10 sec of silence.

**Comment by DavidBuchanan314** [comment]
@kodxana can you upload your mp3 and PNG files here?

**Comment by Vijeth56** [comment]
Hey!
Can anyone explain what's the issue?!
*Cause im a beginner

**Comment by tofel2003** [comment]
This is the error that the app gives you. I did everything according to the instructions.

Image size: 672x378px
Embedded file starts at offset 0x72f
ERROR: Input files too big for cover image resolution.
[sample.zip](https://github.com/DavidBuchanan314/tweetable-polyglot-png/files/6296218/sample.zip)

**Comment by DavidBuchanan314** [comment]
@tofel2003 I would suggest reading the error message, and adjusting your input files accordingly.

**Comment by tofel2003** [comment]
> 
> 
> @ tofel2003 Я бы посоветовал прочитать сообщение об ошибке и соответствующим образом скорректировать ваши входные файлы.

Unfortunately, I don't understand why he doesn't like my mp3 file. If you put in place mp3 for example txt in a zip archive then everything will work but mp3 is NOT

**Comment by DavidBuchanan314** [comment]
Closing this issue do to inactivity, will re-open if someone can upload test files that reproduce the bug.
