### ISSUE TITLE
Not Working Anymore?

### ISSUE THREAD

**Issue by macfrombv** [DavidBuchanan314/tweetable-polyglot-png#8]
I used the tool to make a PNG, and it does work and open. But when uploaded and downloaded through Twitter, it doesn't work anymore. It seems like the image has been compressed to a couple kilobytes. Any ideas? I tried using the original image in the tweet that David posted, but even that didn't work.

**Comment by DavidBuchanan314** [comment]
Still working: https://twitter.com/David3141593/status/1374073253350760459
